// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVX8HCy1nrnGRRvd6FnyEJcUGUaPAzliA',
    appId: '1:923399469156:web:814ae041018838e9970771',
    messagingSenderId: '923399469156',
    projectId: 'doomsday-app',
    authDomain: 'doomsday-app.firebaseapp.com',
    storageBucket: 'doomsday-app.appspot.com',
    measurementId: 'G-5VV56H936J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbSV8U4i1z55w057Y171ICPKQWeY1NWSw',
    appId: '1:923399469156:android:507da1b48fe8d340970771',
    messagingSenderId: '923399469156',
    projectId: 'doomsday-app',
    storageBucket: 'doomsday-app.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVX8HCy1nrnGRRvd6FnyEJcUGUaPAzliA',
    appId: '1:923399469156:web:acdbd6a58988d093970771',
    messagingSenderId: '923399469156',
    projectId: 'doomsday-app',
    authDomain: 'doomsday-app.firebaseapp.com',
    storageBucket: 'doomsday-app.appspot.com',
    measurementId: 'G-DNDD8RHRTR',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCVX8HCy1nrnGRRvd6FnyEJcUGUaPAzliA',
    appId: '1:923399469156:web:90c7e309cebf614a970771',
    messagingSenderId: '923399469156',
    projectId: 'doomsday-app',
    authDomain: 'doomsday-app.firebaseapp.com',
    storageBucket: 'doomsday-app.appspot.com',
    measurementId: 'G-EJS5WDR1YG',
  );

}